server:
  port: 8083

spring:
  kafka: 
    # - KafkaServer in localhost:9092 :
    consumer:
      group-id: TMFC008
    # Apache Kafka Bus
    bootstrap-servers: localhost:9092
    listener:
      poll-timeout: 3000
      concurrency: 3
logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.asyncapi: DEBUG
